/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.audionotification;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiC;

import android.app.Activity;
import android.content.BroadcastReceiver;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.content.ServiceConnection;
import android.content.pm.ApplicationInfo;
import android.os.IBinder;
import android.os.Message;
import android.os.Messenger;
import android.os.RemoteException;
import android.support.v4.content.LocalBroadcastManager;
import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;

@Kroll.module(name = "Tiaudionotification", id = "de.appwerft.audionotification")
public class TiaudionotificationModule extends KrollModule {
	// A reference to the service used to get location updates.
	private NotificationForegroundService notificationForegroundService = null;
	// Standard Debugging variables
	public static final String LCAT = "🎈TiAudioNot";
	
	@Kroll.constant
	public static final int NOTIFICATION_IMPORTANCE_DEFAULT = NotificationManager.IMPORTANCE_DEFAULT;
	@Kroll.constant
	public static final int NOTIFICATION_IMPORTANCE_HIGHT = NotificationManager.IMPORTANCE_HIGH;
	@Kroll.constant
	public static final int NOTIFICATION_IMPORTANCE_LOW = NotificationManager.IMPORTANCE_LOW;
	@Kroll.constant
	public static final int NOTIFICATION_IMPORTANCE_NONE = NotificationManager.IMPORTANCE_NONE;
	@Kroll.constant
	public static final int NOTIFICATION_IMPORTANCE_MIN = NotificationManager.IMPORTANCE_MIN;
	@Kroll.constant
	public static final int NOTIFICATION_IMPORTANCE_MAX = NotificationManager.IMPORTANCE_MAX;
	public TiaudionotificationModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {

	}


}
