/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.audionotification;

import java.util.List;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;

import android.app.NotificationManager;
import android.content.Context;
import android.support.v7.media.MediaRouter;

@Kroll.module(name = "Tiaudionotification", id = "de.appwerft.audionotification")
public class TiaudionotificationModule extends KrollModule {
	// A reference to the service used to get location updates.
	public static final String LCAT = "🎈TiAudioNot";

	@Kroll.constant
	public static final int NOTIFICATION_IMPORTANCE_DEFAULT = NotificationManager.IMPORTANCE_DEFAULT;
	@Kroll.constant
	public static final int NOTIFICATION_IMPORTANCE_HIGHT = NotificationManager.IMPORTANCE_HIGH;
	@Kroll.constant
	public static final int NOTIFICATION_IMPORTANCE_LOW = NotificationManager.IMPORTANCE_LOW;
	@Kroll.constant
	public static final int NOTIFICATION_IMPORTANCE_NONE = NotificationManager.IMPORTANCE_NONE;
	@Kroll.constant
	public static final int NOTIFICATION_IMPORTANCE_MIN = NotificationManager.IMPORTANCE_MIN;
	@Kroll.constant
	public static final int NOTIFICATION_IMPORTANCE_MAX = NotificationManager.IMPORTANCE_MAX;

	@Kroll.constant
	public static final int AUDIO_BLUETOOTH = 0;

	@Kroll.constant
	public static final int AUDIO_SPEAKER = 1;
	@Kroll.constant
	public static final int AUDIO_HEADPHONES = 2;
	@Kroll.constant
	public static final int AUDIO_EARPIECE = 3;
	private MediaRouter mediaRouter;
	private Context ctx;

	public TiaudionotificationModule() {
		super();
		ctx = TiApplication.getInstance().getApplicationContext();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {

	}

	@Kroll.method
	public void setAudioDestination(int destination) {

	}

	@Kroll.method
	public boolean isBluetootAvailable() {
		return true;
	}

	

	@Kroll.method
	public void getAudioRoutes() {
		
	}
}
